# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iosApp
  platform :ios, '15.4' # The version should be the same as the one declared in the build.gradle.kts file
  pod 'composeApp', :path => '../composeApp'

  pod("GoogleSignIn")
  # Others external dependencies used to import them in a Swift file
  #pod 'MQTTClient' # Not needed because I will use the lib in my Kotlin code and not in the Swift code

  # We need to have all pods at the SAME iOS version
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "15.4"
      end
    end
  end
end
